/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.Encounter;
import Model.Patient;
import Model.System;
import Model.VitalSigns;
import javax.swing.JOptionPane;

/**
 *
 * @author prerana
 */
public class EncounterPanel extends javax.swing.JPanel {

    /**
     * Creates new form Encounter
     */
    
    System sys;
    public EncounterPanel(System sys) {
        initComponents();
        this.sys = sys;
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        txtpid = new javax.swing.JTextField();
        lblpid = new javax.swing.JLabel();
        lblbodytemp = new javax.swing.JLabel();
        lblpulserate = new javax.swing.JLabel();
        lblresprate = new javax.swing.JLabel();
        lblbloodpressure = new javax.swing.JLabel();
        txtbodytemp = new javax.swing.JTextField();
        txtpulserate = new javax.swing.JTextField();
        txtresprate = new javax.swing.JTextField();
        lblSystolic = new javax.swing.JLabel();
        txtdateofvisit = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        lbldiastolic = new javax.swing.JLabel();
        lbldateofvisit2 = new javax.swing.JLabel();
        txtdia = new javax.swing.JTextField();
        txtsys = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 204, 204));

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("ENCOUNTER MANAGEMENT ");

        txtpid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpidFocusLost(evt);
            }
        });

        lblpid.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblpid.setText("Patient ID :");

        lblbodytemp.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblbodytemp.setText("Body Temperature :");

        lblpulserate.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblpulserate.setText("Pulse Rate :");

        lblresprate.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblresprate.setText("Respiration Rate :");

        lblbloodpressure.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblbloodpressure.setText("Blood Pressure :");

        txtbodytemp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtbodytempFocusLost(evt);
            }
        });

        txtpulserate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpulserateFocusLost(evt);
            }
        });

        txtresprate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtresprateFocusLost(evt);
            }
        });
        txtresprate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtresprateActionPerformed(evt);
            }
        });

        lblSystolic.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblSystolic.setText("Systolic - ");

        txtdateofvisit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtdateofvisitFocusLost(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(0, 0, 0));
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        lbldiastolic.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbldiastolic.setText("Diastolic -");

        lbldateofvisit2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbldateofvisit2.setText("Date of Visit :");

        txtdia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtdiaFocusLost(evt);
            }
        });

        txtsys.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtsysFocusLost(evt);
            }
        });
        txtsys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsysActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(483, 483, 483)
                .addComponent(lblbloodpressure, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(454, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(287, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblbodytemp, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                        .addComponent(lblpid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblpulserate, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblresprate, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtresprate)
                    .addComponent(txtpulserate)
                    .addComponent(txtbodytemp)
                    .addComponent(txtpid, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE))
                .addContainerGap(288, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(lblSystolic, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtsys, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbldiastolic, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtdia, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(219, 219, 219))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbldateofvisit2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdateofvisit, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(279, 279, 279))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtpid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblpid, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbodytemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblbodytemp, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpulserate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblpulserate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtresprate)
                    .addComponent(lblresprate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addComponent(lblbloodpressure, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSystolic, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbldiastolic, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsys, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdateofvisit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbldateofvisit2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(191, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtresprateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtresprateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtresprateActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        
        for(Patient p : sys.getPatientdir().getListofpatients()) {
            if(p.getUnique_ID().equals(txtpid.getText())) {
                    VitalSigns vs = new VitalSigns(Double.parseDouble(txtbodytemp.getText()),Integer.parseInt(txtpulserate.getText()),Integer.parseInt(txtresprate.getText()),Integer.parseInt(txtsys.getText()), Integer.parseInt( txtdia.getText()));
                    Encounter e = new Encounter(txtpid.getText(), vs);
                    p.getEncounterhistory().getEncounters().add(e);
                    break;
            }
            
        }
        
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtsysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsysActionPerformed

    private void txtpidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpidFocusLost
        // TODO add your handling code here:
        if(!(txtpid.getText().matches("[0-9]"))){
            JOptionPane.showMessageDialog(null, "Invalid input");
            txtpid.setText("");
        }
    }//GEN-LAST:event_txtpidFocusLost

    private void txtbodytempFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtbodytempFocusLost
        // TODO add your handling code here:
        if(!(txtbodytemp.getText().matches("[0-9]+"))){
            JOptionPane.showMessageDialog(null, "Invalid input");
            txtbodytemp.setText("");
        }
    }//GEN-LAST:event_txtbodytempFocusLost

    private void txtpulserateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpulserateFocusLost
        // TODO add your handling code here:
        if(!(txtpulserate.getText().matches("[0-9]+"))){
            JOptionPane.showMessageDialog(null, "Invalid input");
            txtpulserate.setText("");
        }
    }//GEN-LAST:event_txtpulserateFocusLost

    private void txtresprateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtresprateFocusLost
        // TODO add your handling code here:
        if(!(txtresprate.getText().matches("[0-9]+"))){
            JOptionPane.showMessageDialog(null, "Invalid input");
            txtresprate.setText("");
        }
    }//GEN-LAST:event_txtresprateFocusLost

    private void txtsysFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtsysFocusLost
        // TODO add your handling code here:
        if(!(txtsys.getText().matches("[0-9]+"))){
            JOptionPane.showMessageDialog(null, "Invalid input");
            txtsys.setText("");
        }
    }//GEN-LAST:event_txtsysFocusLost

    private void txtdiaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdiaFocusLost
        // TODO add your handling code here:
        if(!(txtdia.getText().matches("[0-9]+"))){
            JOptionPane.showMessageDialog(null, "Invalid input");
            txtdia.setText("");
        }
    }//GEN-LAST:event_txtdiaFocusLost

    private void txtdateofvisitFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdateofvisitFocusLost
        // TODO add your handling code here:
        if(!(txtdateofvisit.getText().matches("^(3[01]|[12][0-9]|0[1-9])-(1[0-2]|0[1-9])-[0-9]{4}$"))){
            JOptionPane.showMessageDialog(null, "Invalid input");
            txtdateofvisit.setText("");
        }
    }//GEN-LAST:event_txtdateofvisitFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JLabel lblSystolic;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblbloodpressure;
    private javax.swing.JLabel lblbodytemp;
    private javax.swing.JLabel lbldateofvisit2;
    private javax.swing.JLabel lbldiastolic;
    private javax.swing.JLabel lblpid;
    private javax.swing.JLabel lblpulserate;
    private javax.swing.JLabel lblresprate;
    private javax.swing.JTextField txtbodytemp;
    private javax.swing.JTextField txtdateofvisit;
    private javax.swing.JTextField txtdia;
    private javax.swing.JTextField txtpid;
    private javax.swing.JTextField txtpulserate;
    private javax.swing.JTextField txtresprate;
    private javax.swing.JTextField txtsys;
    // End of variables declaration//GEN-END:variables
}
