/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.Patient;
import Model.Person;
import Model.System;
import javax.swing.JOptionPane;

/**
 *
 * @author prerana
 */
public class PatientPanel extends javax.swing.JPanel {

    /**
     * Creates new form Patient
     */
    System sys;
    public PatientPanel(System sys) {
        initComponents();
        this.sys = sys;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblUniqueID = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lblpname = new javax.swing.JLabel();
        txtpname = new javax.swing.JTextField();
        lblpid = new javax.swing.JLabel();
        txtpid = new javax.swing.JTextField();
        txtdocname = new javax.swing.JTextField();
        lbldocname = new javax.swing.JLabel();
        lblbloodgroup = new javax.swing.JLabel();
        txtbloodgroup = new javax.swing.JTextField();
        lblmedhistory = new javax.swing.JLabel();
        txtmedhistory = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        lbluid = new javax.swing.JLabel();
        txtuid = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 204, 204));

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("PATIENT MANAGEMENT");

        lblUniqueID.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblUniqueID.setText("UNIQUE ID :");

        txtsearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtsearchFocusLost(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(0, 0, 0));
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(0, 0, 0));
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(0, 0, 0));
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lblpname.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblpname.setText("PATIENT NAME :");

        txtpname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpnameFocusLost(evt);
            }
        });

        lblpid.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblpid.setText("PATIENT ID :");

        txtpid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpidFocusLost(evt);
            }
        });

        txtdocname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtdocnameFocusLost(evt);
            }
        });

        lbldocname.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbldocname.setText("DOCTOR NAME :");

        lblbloodgroup.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblbloodgroup.setText("BLOOD GROUP :");

        txtbloodgroup.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtbloodgroupFocusLost(evt);
            }
        });

        lblmedhistory.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblmedhistory.setText("MEDICAL HISTORY :");

        txtmedhistory.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtmedhistoryFocusLost(evt);
            }
        });

        btnSearch.setBackground(new java.awt.Color(0, 0, 0));
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("SEARCH");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        lbluid.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbluid.setText("UNIQUE ID :");

        txtuid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtuidFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 1121, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblUniqueID, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnSearch)
                .addGap(170, 170, 170))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(161, 161, 161)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
            .addGroup(layout.createSequentialGroup()
                .addGap(349, 349, 349)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblpname, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblpid, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbldocname)
                    .addComponent(lblbloodgroup)
                    .addComponent(lblmedhistory)
                    .addComponent(lbluid, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtuid, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmedhistory, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtbloodgroup, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdocname, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpid, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpname, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUniqueID, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtuid, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbluid, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpname, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpname, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpid, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpid, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldocname, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdocname, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblbloodgroup, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtbloodgroup, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmedhistory, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmedhistory, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(182, 182, 182))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String personID = txtuid.getText().toString();
        
        int flag = 0;
        
        for(Person p : sys.getPersondir().getListofpersons()){
            if(p.getUnique_ID().equals(personID)){
                flag = 1;
                for(Patient q : sys.getPatientdir().getListofpatients()){
                     if(q.getUnique_ID().equals(personID)){ 
                        flag = 0; 
                        break;
                     }
                }
            }
        }
        
        if(flag == 1){
            sys.getPatientdir().getListofpatients().add(new Patient(txtuid.getText(),txtpname.getText(),Integer.parseInt(txtpid.getText()),txtdocname.getText(), txtbloodgroup.getText(), txtmedhistory.getText()));
        }

    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        btnDelete.doClick();
        btnAdd.doClick();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        String personID = txtsearch.getText().toString();
        for(Patient q : sys.getPatientdir().getListofpatients()){
            if(q.getUnique_ID().equals(personID)){
                sys.getPatientdir().getListofpatients().remove(q);
                break;
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String searchbtn = txtsearch.getText();
        for(Patient pa : sys.getPatientdir().getListofpatients()){
        if(pa.getUnique_ID().equals(txtsearch.getText())){
            
              txtuid.setText(pa.getUnique_ID());
              txtpname.setText(pa.getpName());
              txtpid.setText(String.valueOf(pa.getpID()));
              txtdocname.setText(pa.getDocName());
              txtbloodgroup.setText(pa.getBloodGroup());
              txtmedhistory.setText(pa.getMedHistory());
        }
    }       
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtsearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtsearchFocusLost
        // TODO add your handling code here:
        if(!(txtsearch.getText().matches("[A-Z][0-9]{3}"))){
            JOptionPane.showMessageDialog(null, "Invalid input");
            txtsearch.setText("");
        }
    }//GEN-LAST:event_txtsearchFocusLost

    private void txtuidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtuidFocusLost
        // TODO add your handling code here:
        if(!(txtuid.getText().matches("[A-Z]{1}[0-9]{3}"))){
            JOptionPane.showMessageDialog(this, "Invalid input");
            txtuid.setText("");
        }
    }//GEN-LAST:event_txtuidFocusLost

    private void txtpnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpnameFocusLost
        // TODO add your handling code here:
        if(txtpname.getText().trim().length() != 0) {
           if(!(txtpname.getText().matches("[a-zA-Z ]+"))) {
           JOptionPane.showMessageDialog(null, "Invalid name");
           txtpname.setText("");
       } 
       }
    }//GEN-LAST:event_txtpnameFocusLost

    private void txtpidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpidFocusLost
        // TODO add your handling code here:
        if(!(txtpid.getText().matches("[A-Z]{1}[0-9]{3}"))){
            JOptionPane.showMessageDialog(this, "Invalid input");
            txtpid.setText("");
        }
    }//GEN-LAST:event_txtpidFocusLost

    private void txtdocnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdocnameFocusLost
        // TODO add your handling code here:
        if(txtdocname.getText().trim().length() != 0) {
           if(!(txtdocname.getText().matches("[a-zA-Z ]+"))) {
           JOptionPane.showMessageDialog(null, "Invalid name");
           txtdocname.setText("");
       } 
       }
    }//GEN-LAST:event_txtdocnameFocusLost

    private void txtbloodgroupFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtbloodgroupFocusLost
        // TODO add your handling code here:
        if(!(txtbloodgroup.getText().matches("[A],[B],[AB],[O]"))){
            JOptionPane.showMessageDialog(this, "Invalid input");
            txtbloodgroup.setText("");
        }
    }//GEN-LAST:event_txtbloodgroupFocusLost

    private void txtmedhistoryFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtmedhistoryFocusLost
        // TODO add your handling code here:
        if(!(txtmedhistory.getText().matches("[Yes],[No]"))){
            JOptionPane.showMessageDialog(this, "Invalid input");
            txtmedhistory.setText("");
        }
        
    }//GEN-LAST:event_txtmedhistoryFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUniqueID;
    private javax.swing.JLabel lblbloodgroup;
    private javax.swing.JLabel lbldocname;
    private javax.swing.JLabel lblmedhistory;
    private javax.swing.JLabel lblpid;
    private javax.swing.JLabel lblpname;
    private javax.swing.JLabel lbluid;
    private javax.swing.JTextField txtbloodgroup;
    private javax.swing.JTextField txtdocname;
    private javax.swing.JTextField txtmedhistory;
    private javax.swing.JTextField txtpid;
    private javax.swing.JTextField txtpname;
    private javax.swing.JTextField txtsearch;
    private javax.swing.JTextField txtuid;
    // End of variables declaration//GEN-END:variables
}
