/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.Product;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author prerana
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    
    Product product;
    public CreateJPanel(Product product) {
        initComponents();
        this.product = product;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        lblDob = new javax.swing.JLabel();
        lblgeodata = new javax.swing.JLabel();
        lblph_num = new javax.swing.JLabel();
        lblfax_num = new javax.swing.JLabel();
        lblemail = new javax.swing.JLabel();
        lblssn = new javax.swing.JLabel();
        lblmed_num = new javax.swing.JLabel();
        lblhealthPlan_num = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtdob = new javax.swing.JTextField();
        txtgeodata = new javax.swing.JTextField();
        txtph_num = new javax.swing.JTextField();
        txtfax_num = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtssn = new javax.swing.JTextField();
        txtmed_num = new javax.swing.JTextField();
        txthealthPlan_num = new javax.swing.JTextField();
        lblbank_details = new javax.swing.JLabel();
        lbllicense = new javax.swing.JLabel();
        lblvehicle_ID = new javax.swing.JLabel();
        lbldevice_ID = new javax.swing.JLabel();
        lbllinkedIN = new javax.swing.JLabel();
        lblip_Address = new javax.swing.JLabel();
        lblphoto = new javax.swing.JLabel();
        lbluID = new javax.swing.JLabel();
        txtbank_details = new javax.swing.JTextField();
        txtlicense = new javax.swing.JTextField();
        txtvehicle_ID = new javax.swing.JTextField();
        txtdevice_ID = new javax.swing.JTextField();
        txtlinkedIN = new javax.swing.JTextField();
        txtip_Address = new javax.swing.JTextField();
        txtuID = new javax.swing.JTextField();
        btnsubmit = new javax.swing.JButton();
        btnChooseFile = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("PERSONAL INFORMATION");

        lblname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblname.setText("Name:");

        lblDob.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDob.setText("Date of Birth:");

        lblgeodata.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblgeodata.setText("Geographic Data:");

        lblph_num.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblph_num.setText("Phone Number:");

        lblfax_num.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblfax_num.setText("Fax Number:");

        lblemail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblemail.setText("Email Address:");

        lblssn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblssn.setText("Social Security Number:");

        lblmed_num.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblmed_num.setText("Medical Record Number:");

        lblhealthPlan_num.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblhealthPlan_num.setText("Health Plan Number:");

        txtname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnameFocusLost(evt);
            }
        });

        txtdob.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtdobFocusLost(evt);
            }
        });

        txtgeodata.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtgeodataFocusLost(evt);
            }
        });

        txtph_num.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtph_numFocusLost(evt);
            }
        });

        txtfax_num.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtfax_numFocusLost(evt);
            }
        });

        txtemail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtemailFocusLost(evt);
            }
        });

        txtssn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtssnFocusLost(evt);
            }
        });

        txtmed_num.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtmed_numFocusLost(evt);
            }
        });
        txtmed_num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmed_numActionPerformed(evt);
            }
        });

        txthealthPlan_num.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txthealthPlan_numFocusLost(evt);
            }
        });
        txthealthPlan_num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthealthPlan_numActionPerformed(evt);
            }
        });

        lblbank_details.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblbank_details.setText("Bank Account Number:");

        lbllicense.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbllicense.setText("License Number:");

        lblvehicle_ID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblvehicle_ID.setText("Vehicle ID:");

        lbldevice_ID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbldevice_ID.setText("Device ID:");

        lbllinkedIN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbllinkedIN.setText("LinkedIN URL:");

        lblip_Address.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblip_Address.setText("IP Address:");

        lblphoto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblphoto.setText("Person photo:");

        lbluID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbluID.setText("Other Unique ID:");

        txtbank_details.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtbank_detailsFocusLost(evt);
            }
        });
        txtbank_details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbank_detailsActionPerformed(evt);
            }
        });

        txtlicense.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtlicenseFocusLost(evt);
            }
        });
        txtlicense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlicenseActionPerformed(evt);
            }
        });

        txtvehicle_ID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtvehicle_IDFocusLost(evt);
            }
        });
        txtvehicle_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvehicle_IDActionPerformed(evt);
            }
        });

        txtdevice_ID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtdevice_IDFocusLost(evt);
            }
        });
        txtdevice_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdevice_IDActionPerformed(evt);
            }
        });

        txtlinkedIN.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtlinkedINFocusLost(evt);
            }
        });
        txtlinkedIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlinkedINActionPerformed(evt);
            }
        });

        txtip_Address.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtip_AddressFocusLost(evt);
            }
        });
        txtip_Address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtip_AddressActionPerformed(evt);
            }
        });

        txtuID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtuIDFocusLost(evt);
            }
        });
        txtuID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuIDActionPerformed(evt);
            }
        });

        btnsubmit.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnsubmit.setText("SUBMIT");
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });

        btnChooseFile.setText("Choose File");
        btnChooseFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 1319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblname)
                            .addComponent(lblDob)
                            .addComponent(lblgeodata)
                            .addComponent(lblfax_num)
                            .addComponent(lblssn)
                            .addComponent(lblmed_num)
                            .addComponent(lblhealthPlan_num)
                            .addComponent(lblph_num)
                            .addComponent(lblemail))
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdob, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtgeodata, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtph_num, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfax_num, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtssn, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmed_num, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txthealthPlan_num, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(180, 180, 180)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblbank_details)
                            .addComponent(lbllicense)
                            .addComponent(lbllinkedIN)
                            .addComponent(lblip_Address)
                            .addComponent(lblphoto)
                            .addComponent(lbluID)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbldevice_ID)
                                .addComponent(lblvehicle_ID)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtip_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtlinkedIN, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtdevice_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtvehicle_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtlicense, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtbank_details, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtuID, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(180, 180, 180)
                                .addComponent(btnChooseFile))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(492, 492, 492)
                        .addComponent(btnsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblname)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblbank_details)
                    .addComponent(txtbank_details, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDob)
                            .addComponent(txtdob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtlicense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblgeodata)
                            .addComponent(txtgeodata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblph_num)
                            .addComponent(txtph_num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblfax_num)
                            .addComponent(txtfax_num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblemail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtssn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblssn))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblmed_num)
                            .addComponent(txtmed_num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblhealthPlan_num)
                            .addComponent(txthealthPlan_num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lbllicense)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtvehicle_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblvehicle_ID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtdevice_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbldevice_ID))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtlinkedIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbllinkedIN))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtip_Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblip_Address))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblphoto)
                            .addComponent(btnChooseFile))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtuID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbluID))))
                .addGap(52, 52, 52)
                .addComponent(btnsubmit)
                .addContainerGap(307, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtmed_numActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmed_numActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmed_numActionPerformed

    private void txthealthPlan_numActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthealthPlan_numActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthealthPlan_numActionPerformed

    private void txtbank_detailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbank_detailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbank_detailsActionPerformed

    private void txtlicenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlicenseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlicenseActionPerformed

    private void txtvehicle_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvehicle_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvehicle_IDActionPerformed

    private void txtdevice_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdevice_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdevice_IDActionPerformed

    private void txtlinkedINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlinkedINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlinkedINActionPerformed

    private void txtip_AddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtip_AddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtip_AddressActionPerformed

    private void txtuIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuIDActionPerformed

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
        // TODO add your handling code here:
        String name = txtname.getText();
        if (name.equals("")) {
            JOptionPane.showMessageDialog(this, "Name is empty");
            return;
        }
        product.setName(txtname.getText());
            
        String dob = txtdob.getText();
        if (dob.equals("")) {
            JOptionPane.showMessageDialog(this, "DOB is empty");
            return;
        }
        product.setDob(txtdob.getText());
        
        String geodata = txtgeodata.getText();
        if (geodata.equals("")) {
            JOptionPane.showMessageDialog(this, "Geographical Data is empty");
            return;
        }
        product.setGeodata(txtgeodata.getText());
        
        //product.setPh_num(txtph_num.getText());
        String phnumstr = txtph_num.getText();
        int phnumint = Integer.parseInt(phnumstr);
        product.setPh_num(phnumint);
        
        //product.setFax_num(txtfax_num.getText());
        String faxnumstr = txtfax_num.getText();
        int faxnumint = Integer.parseInt(faxnumstr);
        product.setFax_num(faxnumint);
        
        String email = txtemail.getText();
        if (email.equals("")) {
            JOptionPane.showMessageDialog(this, "Email ID field is empty");
            return;
        }
        product.setEmail(txtemail.getText());
        
//        String ssn = txtssn.getText();
//        if (ssn.equals("")) {
//            JOptionPane.showMessageDialog(this, "SSN is empty");
//            return;
//        }
        product.setSsn(txtssn.getText());
        
        String med_num = txtmed_num.getText();
        if (med_num.equals("")) {
            JOptionPane.showMessageDialog(this, "Medical Record Number field is empty");
            return;
        }
        product.setMed_num(txtmed_num.getText());
        
        String healthPlan_num = txthealthPlan_num.getText();
        if (healthPlan_num.equals("")) {
            JOptionPane.showMessageDialog(this, "Health Plan Beneficiary Number field is empty");
            return;
        }
        product.setHealtthPlan_num(txthealthPlan_num.getText());
        
        //product.setBank_details(txtbank_details.getText());
        String bankaccstr = txtbank_details.getText();
        try{
            int bankaccint = Integer.parseInt(bankaccstr);
            product.setBank_details(bankaccint);
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(this, "Invalid bank account number");
            return;
        }
        
        String license = txtlicense.getText();
        if (license.equals("")) {
            JOptionPane.showMessageDialog(this, "License is empty");
            return;
        }
        product.setLicense(txtlicense.getText());
        
        String vehicle_ID = txtvehicle_ID.getText();
        if (vehicle_ID.equals("")) {
            JOptionPane.showMessageDialog(this, "Vehicle ID is empty");
            return;
        }
        product.setVehicle_ID(txtvehicle_ID.getText());
        
        String device_ID = txtdevice_ID.getText();
        if (device_ID.equals("")) {
            JOptionPane.showMessageDialog(this, "Device ID field is empty");
            return;
        }
        product.setDevice_ID(txtdevice_ID.getText());
        
        String linkedIN = txtlinkedIN.getText();
        if (linkedIN.equals("")) {
            JOptionPane.showMessageDialog(this, "LinkedIN url field is empty");
            return;
        }
        product.setLinkedIN(txtlinkedIN.getText());
        
        String ip_Address = txtip_Address.getText();
        if (ip_Address.equals("")) {
            JOptionPane.showMessageDialog(this, "IP Address field is empty");
            return;
        }
        product.setIp_address(txtip_Address.getText());
        //product.setPhoto(txtphoto.getText());
        
        String uID = txtuID.getText();
        if (uID.equals("")) {
            JOptionPane.showMessageDialog(this, "Unique Identity field is empty");
            return;
        }
        product.setuID(txtuID.getText());
        
        JOptionPane.showMessageDialog(this, "Person Information saved.");
    }//GEN-LAST:event_btnsubmitActionPerformed

    private void txtnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnameFocusLost
        // TODO add your handling code here:
       if(txtname.getText().trim().length() != 0) {
           if(!(txtname.getText().matches("[a-zA-Z ]+"))) {
           JOptionPane.showMessageDialog(null, "Invalid name");
           txtname.setText("");
       } 
       }
    }//GEN-LAST:event_txtnameFocusLost

    private void txtdobFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdobFocusLost
        // TODO add your handling code here:
        if(!(txtdob.getText().matches("^(1[0-2]|0[1-9])-(3[01]|[12][0-9]|0[1-9])-[0-9]{4}$"))){
            JOptionPane.showMessageDialog(null, "Invalid input");
            txtdob.setText("");
        }
    }//GEN-LAST:event_txtdobFocusLost

    private void txtemailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtemailFocusLost
        // TODO add your handling code here:
        if(!(txtemail.getText().matches("^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$"))) {
            JOptionPane.showMessageDialog(null, "Enter a valid email address!");
            txtemail.setText("");
        }
    }//GEN-LAST:event_txtemailFocusLost

    private void txtgeodataFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtgeodataFocusLost
        // TODO add your handling code here:
        if(!(txtgeodata.getText().matches("[a-zA-Z0-9,.]+"))) {
           JOptionPane.showMessageDialog(null, "Location not found. ");
           txtgeodata.setText("");
       } 
    }//GEN-LAST:event_txtgeodataFocusLost

    private void txtph_numFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtph_numFocusLost
        // TODO add your handling code here:
        if(txtph_num.getText().length() != 10) {
        if(!(txtph_num.getText().matches("[0-9]"))) {
           JOptionPane.showMessageDialog(null, "invalid Phone number.");
           txtph_num.setText("");
        }
        } 
    }//GEN-LAST:event_txtph_numFocusLost

    private void txtfax_numFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfax_numFocusLost
        // TODO add your handling code here:
         if(txtfax_num.getText().length() != 0) {
        if(!(txtph_num.getText().matches("[0-9]+"))) {
           JOptionPane.showMessageDialog(null, "invalid Fax number.");
           txtfax_num.setText("");
        }
        } 
    }//GEN-LAST:event_txtfax_numFocusLost

    private void txtssnFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtssnFocusLost
        // TODO add your handling code here:
        if(!(txtssn.getText().matches("^(?!666|000|9\\\\d{2})\\\\d{3}\"\n" +"+ \"-(?!00)\\\\d{2}-\"\n" +"+\"(?!0{4})\\\\d{4}$\""))) {
           JOptionPane.showMessageDialog(null, "invalid Social Number.");
           //txtssn.setText("");
        }
    }//GEN-LAST:event_txtssnFocusLost

    private void txtmed_numFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtmed_numFocusLost
        // TODO add your handling code here:
         if(txtmed_num.getText().trim().length() != 10) {
             JOptionPane.showMessageDialog(null, "Enter your Medical Record number!");
             txtmed_num.setText("");
         
         }
    }//GEN-LAST:event_txtmed_numFocusLost

    private void txthealthPlan_numFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txthealthPlan_numFocusLost
        // TODO add your handling code here:
        if(txthealthPlan_num.getText().trim().length() != 10) {
             JOptionPane.showMessageDialog(null, "Enter a valid Health Plan Beneficiary number!");
             txthealthPlan_num.setText("");
         
         }
    }//GEN-LAST:event_txthealthPlan_numFocusLost

    private void txtbank_detailsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtbank_detailsFocusLost
        // TODO add your handling code here:
        //if(txtbank_details.getText().trim().length() != 0) {
            if(!(txtbank_details.getText().matches("[A-Z0-9]+"))){
             JOptionPane.showMessageDialog(null, "Enter a valid Bank Account number!");
             //txtbank_details.setText("");
            //}
         }
    }//GEN-LAST:event_txtbank_detailsFocusLost

    private void txtlicenseFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtlicenseFocusLost
        // TODO add your handling code here:
        //if(txtlicense.getText().trim().length() != 0) {
            if(txtlicense.getText().matches("[A-Z0-9]+")){
             JOptionPane.showMessageDialog(null, "Enter a valid License number");
             //txtlicense.setText("");
            //}
         }
    }//GEN-LAST:event_txtlicenseFocusLost

    private void txtvehicle_IDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtvehicle_IDFocusLost
        // TODO add your handling code here:
        if(txtvehicle_ID.getText().trim().length() == 0) {
             JOptionPane.showMessageDialog(null, "Vehicle ID Missing");
             //txtvehicle_ID.setText("");
         
         }
    }//GEN-LAST:event_txtvehicle_IDFocusLost

    private void txtdevice_IDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdevice_IDFocusLost
        // TODO add your handling code here:
        if(txtdevice_ID.getText().trim().length() == 0) {
             JOptionPane.showMessageDialog(null, "Enter Device ID");
             //txtdevice_ID.setText("");
         
         }
    }//GEN-LAST:event_txtdevice_IDFocusLost

    private void txtlinkedINFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtlinkedINFocusLost
        // TODO add your handling code here:
        if(!(txtlinkedIN.getText().matches("http://www.linkedin.com/in/[A-Za-z0-9]+"))) {
            JOptionPane.showMessageDialog(null, "Enter a valid url");
            //txtlinkedIN.setText("");
        }
    }//GEN-LAST:event_txtlinkedINFocusLost

    private void txtip_AddressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtip_AddressFocusLost
        // TODO add your handling code here:
        if(!(txtip_Address.getText().matches("[0-9]{3}.[0-9]{3}.[0-9}{3}.[0-9]{3}"))) {
            JOptionPane.showMessageDialog(null, "Enter a valid IP Address");
            //txtip_Address.setText("");
        }
    }//GEN-LAST:event_txtip_AddressFocusLost

    private void txtuIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtuIDFocusLost
        // TODO add your handling code here:
        if(txtuID.getText().trim().length() == 0) {
            if(txtuID.getText().matches("[A-Z0-9]+")){
             JOptionPane.showMessageDialog(null, "Please enter unique ID");
             //txtuID.setText("");
         
         }
        }
        
    }//GEN-LAST:event_txtuIDFocusLost

    private void btnChooseFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseFileActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
               File selectedFile = fileChooser.getSelectedFile();
               product.setPhoto(selectedFile);
        }
    }//GEN-LAST:event_btnChooseFileActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChooseFile;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JLabel lblDob;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblbank_details;
    private javax.swing.JLabel lbldevice_ID;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblfax_num;
    private javax.swing.JLabel lblgeodata;
    private javax.swing.JLabel lblhealthPlan_num;
    private javax.swing.JLabel lblip_Address;
    private javax.swing.JLabel lbllicense;
    private javax.swing.JLabel lbllinkedIN;
    private javax.swing.JLabel lblmed_num;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblph_num;
    private javax.swing.JLabel lblphoto;
    private javax.swing.JLabel lblssn;
    private javax.swing.JLabel lbluID;
    private javax.swing.JLabel lblvehicle_ID;
    private javax.swing.JTextField txtbank_details;
    private javax.swing.JTextField txtdevice_ID;
    private javax.swing.JTextField txtdob;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfax_num;
    private javax.swing.JTextField txtgeodata;
    private javax.swing.JTextField txthealthPlan_num;
    private javax.swing.JTextField txtip_Address;
    private javax.swing.JTextField txtlicense;
    private javax.swing.JTextField txtlinkedIN;
    private javax.swing.JTextField txtmed_num;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtph_num;
    private javax.swing.JTextField txtssn;
    private javax.swing.JTextField txtuID;
    private javax.swing.JTextField txtvehicle_ID;
    // End of variables declaration//GEN-END:variables
}
