/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.Product;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author prerana
 */
public class DisplayJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DisplayJPanel
     */
    Product product;
    public DisplayJPanel(Product product) throws IOException {
        initComponents();
        this.product = product;
        
        displayInformation();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblph_num = new javax.swing.JLabel();
        lblhealthPlan_num = new javax.swing.JLabel();
        txtmed_num = new javax.swing.JTextField();
        lblfax_num = new javax.swing.JLabel();
        lblmed_num = new javax.swing.JLabel();
        lblemail = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        txtssn = new javax.swing.JTextField();
        lblgeodata = new javax.swing.JLabel();
        txtgeodata = new javax.swing.JTextField();
        lblDob = new javax.swing.JLabel();
        lblssn = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        txtfax_num = new javax.swing.JTextField();
        txtdob = new javax.swing.JTextField();
        txthealthPlan_num = new javax.swing.JTextField();
        lblbank_details = new javax.swing.JLabel();
        txtph_num = new javax.swing.JTextField();
        lblname = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        lbllicense = new javax.swing.JLabel();
        lblvehicle_ID = new javax.swing.JLabel();
        lbldevice_ID = new javax.swing.JLabel();
        lbllinkedIN = new javax.swing.JLabel();
        lblip_Address = new javax.swing.JLabel();
        lblphoto = new javax.swing.JLabel();
        lbluID = new javax.swing.JLabel();
        txtbank_details = new javax.swing.JTextField();
        txtlicense = new javax.swing.JTextField();
        txtvehicle_ID = new javax.swing.JTextField();
        txtdevice_ID = new javax.swing.JTextField();
        txtlinkedIN = new javax.swing.JTextField();
        txtip_Address = new javax.swing.JTextField();
        txtuID = new javax.swing.JTextField();
        lblphotodisplay = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 255));

        lblph_num.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblph_num.setText("Phone Number:");

        lblhealthPlan_num.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblhealthPlan_num.setText("Health Plan Number:");

        txtmed_num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmed_numActionPerformed(evt);
            }
        });

        lblfax_num.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblfax_num.setText("Fax Number:");

        lblmed_num.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblmed_num.setText("Medical Record Number:");

        lblemail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblemail.setText("Email Address:");

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("PERSONAL INFORMATION");

        lblgeodata.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblgeodata.setText("Geographic Data:");

        lblDob.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDob.setText("Date of Birth:");

        lblssn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblssn.setText("Social Security Number:");

        txthealthPlan_num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthealthPlan_numActionPerformed(evt);
            }
        });

        lblbank_details.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblbank_details.setText("Bank Account Number:");

        lblname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblname.setText("Name:");

        lbllicense.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbllicense.setText("License Number:");

        lblvehicle_ID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblvehicle_ID.setText("Vehicle ID:");

        lbldevice_ID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbldevice_ID.setText("Device ID:");

        lbllinkedIN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbllinkedIN.setText("LinkedIN URL:");

        lblip_Address.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblip_Address.setText("IP Address:");

        lblphoto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblphoto.setText("Person photo:");

        lbluID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbluID.setText("Other Unique ID:");

        txtbank_details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbank_detailsActionPerformed(evt);
            }
        });

        txtlicense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlicenseActionPerformed(evt);
            }
        });

        txtvehicle_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvehicle_IDActionPerformed(evt);
            }
        });

        txtdevice_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdevice_IDActionPerformed(evt);
            }
        });

        txtlinkedIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlinkedINActionPerformed(evt);
            }
        });

        txtip_Address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtip_AddressActionPerformed(evt);
            }
        });

        txtuID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 1319, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblname)
                            .addComponent(lblDob)
                            .addComponent(lblgeodata)
                            .addComponent(lblph_num)
                            .addComponent(lblfax_num)
                            .addComponent(lblemail)
                            .addComponent(lblssn)
                            .addComponent(lblmed_num)
                            .addComponent(lblhealthPlan_num))
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdob, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtgeodata, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtph_num, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfax_num, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtssn, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmed_num, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txthealthPlan_num, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(180, 180, 180)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblbank_details)
                            .addComponent(lbllicense)
                            .addComponent(lblvehicle_ID)
                            .addComponent(lbldevice_ID)
                            .addComponent(lbllinkedIN)
                            .addComponent(lblip_Address)
                            .addComponent(lbluID)
                            .addComponent(lblphoto))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtuID, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                            .addComponent(txtip_Address, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                            .addComponent(txtlinkedIN, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                            .addComponent(txtdevice_ID, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                            .addComponent(txtvehicle_ID, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                            .addComponent(txtlicense, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                            .addComponent(txtbank_details, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                            .addComponent(lblphotodisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblname)
                                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblbank_details)
                                    .addComponent(txtbank_details, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblDob)
                                    .addComponent(txtdob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbllicense)
                                    .addComponent(txtlicense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblgeodata)
                                    .addComponent(txtgeodata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblvehicle_ID)
                                    .addComponent(txtvehicle_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblph_num)
                                    .addComponent(txtph_num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbldevice_ID)
                                    .addComponent(txtdevice_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblfax_num)
                                    .addComponent(txtfax_num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbllinkedIN)
                                    .addComponent(txtlinkedIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblemail))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblip_Address)
                                .addComponent(txtip_Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblssn))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lbluID)))
                        .addGap(5, 5, 5))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtssn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtuID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblmed_num)
                            .addComponent(txtmed_num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblhealthPlan_num)
                            .addComponent(txthealthPlan_num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblphoto))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lblphotodisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(310, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtmed_numActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmed_numActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmed_numActionPerformed

    private void txthealthPlan_numActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthealthPlan_numActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthealthPlan_numActionPerformed

    private void txtbank_detailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbank_detailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbank_detailsActionPerformed

    private void txtlicenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlicenseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlicenseActionPerformed

    private void txtvehicle_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvehicle_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvehicle_IDActionPerformed

    private void txtdevice_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdevice_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdevice_IDActionPerformed

    private void txtlinkedINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlinkedINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlinkedINActionPerformed

    private void txtip_AddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtip_AddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtip_AddressActionPerformed

    private void txtuIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuIDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDob;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblbank_details;
    private javax.swing.JLabel lbldevice_ID;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblfax_num;
    private javax.swing.JLabel lblgeodata;
    private javax.swing.JLabel lblhealthPlan_num;
    private javax.swing.JLabel lblip_Address;
    private javax.swing.JLabel lbllicense;
    private javax.swing.JLabel lbllinkedIN;
    private javax.swing.JLabel lblmed_num;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblph_num;
    private javax.swing.JLabel lblphoto;
    private javax.swing.JLabel lblphotodisplay;
    private javax.swing.JLabel lblssn;
    private javax.swing.JLabel lbluID;
    private javax.swing.JLabel lblvehicle_ID;
    private javax.swing.JTextField txtbank_details;
    private javax.swing.JTextField txtdevice_ID;
    private javax.swing.JTextField txtdob;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfax_num;
    private javax.swing.JTextField txtgeodata;
    private javax.swing.JTextField txthealthPlan_num;
    private javax.swing.JTextField txtip_Address;
    private javax.swing.JTextField txtlicense;
    private javax.swing.JTextField txtlinkedIN;
    private javax.swing.JTextField txtmed_num;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtph_num;
    private javax.swing.JTextField txtssn;
    private javax.swing.JTextField txtuID;
    private javax.swing.JTextField txtvehicle_ID;
    // End of variables declaration//GEN-END:variables

    private void displayInformation() throws IOException {
        
        txtname.setText(product.getName());
        txtdob.setText(product.getDob());
        txtgeodata.setText(product.getGeodata());
        
        //txtph_num.setText(product.getPh_num());        
        int phnumint = product.getPh_num();
        String phnumstr = String.valueOf(phnumint);
        txtph_num.setText(phnumstr);
        
        //txtfax_num.setText(product.getFax_num());
        int faxnumint = product.getFax_num();
        String faxnumstr = String.valueOf(faxnumint);
        txtfax_num.setText(faxnumstr);
        //JOptionPane.showMessageDialog(this, product.getEmail());
        txtemail.setText(product.getEmail());
        txtssn.setText(product.getSsn());
        txtmed_num.setText(product.getMed_num());
        txthealthPlan_num.setText(product.getHealtthPlan_num());
        
        //txtbank_details.setText(product.getBank_details());
        int bankaccint = product.getBank_details();
        String bankaccstr = String.valueOf(bankaccint);
        txtbank_details.setText(bankaccstr);
        
        txtlicense.setText(product.getLicense());
        txtvehicle_ID.setText(product.getVehicle_ID());
        txtdevice_ID.setText(product.getDevice_ID());
        txtlinkedIN.setText(product.getLinkedIN());
        txtip_Address.setText(product.getIp_address());
        //txtphoto.setText(product.getPhoto());
        txtuID.setText(product.getuID());
        BufferedImage wPic = ImageIO.read(product.getPhoto());
        lblphotodisplay.setIcon(new ImageIcon(new ImageIcon(wPic).getImage().getScaledInstance(200, 200, Image.SCALE_DEFAULT)));
        lblphotodisplay.setText("");
        
    }
}
